---
abstract: 'undo what the template engine does'
author:
  - 'Stanislaw Pusep <stas@sysd.org>'
build_requires:
  Data::Dumper: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  FindBin: 0
  Path::Class: 0
  Test::More: 0
  Test::Requires: 0
  perl: 5.006
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300013, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Untemplate
requires:
  Any::Moose: 0
  Digest::SHA: 0
  Getopt::Long: 0
  HTML::TreeBuilder: 0
  IO::Interactive: 0
  JSON::XS: 0
  MouseX::NonMoose: 0
  Pod::Usage: 0
  Term::ANSIColor: 0
  Tie::IxHash: 0
  common::sense: 0
  open: 0
  overload: 0
  perl: 5.010
  strict: 0
resources:
  bugtracker: https://github.com/creaktive/HTML-Untemplate/issues
  homepage: https://github.com/creaktive/HTML-Untemplate
  repository: git://github.com/creaktive/HTML-Untemplate.git
version: 0.002
